import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import LoginListener from "@/hooks/LoginListener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="zen-kaku-gothic-new">
        {children}
        <LoginListener />
      </body>
    </html>
  );
}
